
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Datadog
  annotations:
    github.com/project-slug: Priyatamvemulapalli/DATADOG
    datadoghq.com/dashboard-url: https://p.us5.datadoghq.com/sb/c64d9ffa-d2c6-11ed-abbc-da7ad0900005-41d700be592bc51b58bbf6461dadc527
    datadoghq.com/graph-token: 17edc3b7aab1cb142d5985
spec:
  type: other
  lifecycle: unknown
  owner: users
