
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Datadog
  annotations:
    github.com/project-slug: Priyatamvemulapalli/DATADOG
    jira/project-key: LOAN
    jenkins.io/job-full-name: "jtp"
    datadoghq.com/dashboard-url: https://p.datadoghq.eu/sb/d388a742-d374-11ed-86bc-da7ad0900005-63fd6cff125b0594279594356fd4524a
    datadoghq.com/graph-token: a6a7d87797458a439f81b8323f665145ae7391d56786c3cfd105429f4fe23ca9
spec:
  type: other
  lifecycle: unknown
  owner: users
